name: claro_radios
description: Internet radio streaming application.
publish_to: 'none'
version: 2.0.7

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  imusica_design_system:
    git:
      url: https://github.com/iMusica/plataforma-design-system-flutter.git
      ref: master
  audio_service: ^0.18.12
  audio_session: ^0.1.18
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  equatable: ^2.0.5
  firebase_analytics: ^10.7.2
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.4.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_html: ^3.0.0-beta.2
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.6
  go_router: ^13.0.1
  http: ^1.1.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  #!This lib is in local to use a version that was not merged yet
  just_audio:
    path: ./just_audio/just_audio
  package_info_plus: ^5.0.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  sign_in_with_apple: ^5.0.0
  url_launcher: ^6.2.1
  webview_flutter: ^4.4.4

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
    - assets/icons/

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: pt
  arb_dir: lib/core/l10n/arb
  output_dir: lib/core/l10n/generated
  use_deferred_loading: false
